mybatis-plus:
  # mapper-locations: classpath:/mapper/*Mapper.xml
  # typeAliasesPackage: kled.test.dal.entity
  global-config:
    # 3.x配置需增加一级"db-config"
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #驼峰下划线转换
      db-column-underline: true
